info:
  app:
    name: similar-products
    version: 1.0.0

openapi:
  enabled: true
  info:
    title: ${info.app.name}
    description: ${info.app.description}
    version: ${info.app.version}
    contact:
      name: Support Napptilus
      email: contact-support@napptilus.com
    license:
      name: Copyright Melia Hotels International

# Configuracion del Microservicio
spring:
  application:
    name: similarproducts
    description: Microservice for similar products availability

# Configuracion server
server:
  port: 5000
  error:
    include-message: always
    include-exception: true

# Configuracion Feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# Configuracion de la API de Productos Similares
existing-apis:
  name: existingApis
  url:
    base: http://localhost:3001
    product: /product/{productId}
    similarIds: /product/{productId}/similarids